version: "3.7"

services:
  figaro:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_gateway"
      - "traefik.http.routers.figaro.rule=PathPrefix(`/figaro`)"
      - "traefik.http.services.figaro.loadbalancer.server.port=80"


    networks:
      - traefik

  gorafi:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_gateway"
      - "traefik.http.routers.gorafi.rule=PathPrefix(`/gorafi`)"
      - "traefik.http.services.gorafi.loadbalancer.server.port=80"

    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik_gateway
